[package]
name = "mythmallow-core-constants"
version = "0.1.0"
edition = "2021"

[dependencies]
mythmallow-core-dependencies = { path = "../dependencies" }

[features]
development = [
    "mythmallow-core-dependencies/development",
]

[lints]
workspace = true
